export default [
    'någonsin spelat pajas på skolan eller jobbet',
    'stulit något',
    'missat ett flyg',
    ' någonsin fyllt mitt ex',
    'kört motorcykel',
    'förlorat ett vad',
    'någonsin gått vilse ensam i ett främmande land',
    'mutat någon',
    ' någonsin gått i skinny-dipping',
    'någonsin varit otrogen mot någon',
    'sjungit karaoke',
    'brutit ett ben',
    'någonsin bott ensam',
    'varit på en yacht',
    'varit på tv',
    'varit på en blind date',
    'ljugit för polisen',
    'tatuerat mig',
    'använt ett falskt ID',
    'gjort slut med någon',
    'någonsin blivit seriöst bakfull',
    'använt någon annans tandborste',
    'täppt till någon annans toalett',
    'någonsin somnat offentligt',
    'någonsin kysst någon offentligt',
    'någonsin slagits offentligt',
    'någonsin ätit och rusat',
    'vunnit på lotteriet',
    'behövt gå till domstol',
    'varit på ett målbröllop',
    'ljugit för en chef',
    'någonsin kraschat ett bröllop',
    'någonsin kysst mer än en person på 24 timmar',
    'skämtat någon',
    'någonsin haft ett one-night stand',
    'skänkt bort en gåva',
    'trollat ​​någon på sociala medier',
    'någonsin klättrat ut genom ett fönster',
    'någonsin kört över en trottoarkant',
    'någonsin skrattat så mycket att jag kissade på byxorna som vuxen',
    'någonsin kommit på fel tåg eller buss',
    'skickat en sext',
    'någonsin förbannat på en plats för tillbedjan',
    'snokat igenom någons saker',
    'testat marijuana',
    'någonsin gått 24 timmar utan att duscha',
    'någonsin behövt ta en promenad av skam',
    'någonsin åkt på en ensamsemester',
    'åkt på en roadtrip',
    'någonsin ätit en hel pizza själv',
    'någonsin räddat ett liv',
    'tatuerat mig',
    'någonsin velat vara med i en dokusåpa',
    'anlagt en eld',
    'någonsin blivit stoppad av flygplatssäkerhet',
    'någonsin blivit viral på nätet',
    'någonsin lämnat tuggummi i ett offentligt utrymme',
    'sovit utomhus en hel natt',
    'sprungit ett maraton',
    'någonsin gett/fått en lapdance',
    'någonsin hållit ett tal inför 100 personer eller fler',
    'slappnat av i en offentlig pool',
    'någonsin ljugit för min bästa vän om vem jag var med',
    'någonsin varit i en Disneypark',
    'haft en trekant',
    'lämnat någon på läsning',
    'någonsin somnat under sex',
    'ljugit om min ålder',
    'någonsin hittat på en berättelse om någon som inte var verklig',
    'någonsin trott att något var hemsökt',
    'någonsin deltagit i en protest',
    'någonsin haft sömnförlamning',
    'någonsin varit alibi för en lögnaktig vän',
    'någonsin dragit en helnatter',
    'någonsin spelat rollspel',
    'ångrat en ursäkt',
    'någonsin låtsats som att jag var trött på uppmärksamhet',
    'någonsin ogillat något som jag lagat',
    'någonsin tagit bort ett inlägg på sociala medier för att det inte fått tillräckligt många likes',
    'någonsin spenderat mer än 100 dollar på en topp',
    'kastat en drink på någon',
    'någonsin burit någon annans underkläder',
    'rest till Europa',
    'testat en trendig diet',
    'någonsin gått på en strippklubb',
    'någonsin bråkat en hel serie på en dag',
    'testat psykedelika',
    'någonsin träffat någon känd',
    'någonsin blivit streaking',
    'varit med i ett idrottslag',
    'någonsin maxat ett kreditkort',
    'varit blackout full',
    'varit förlovad',
    'gift mig',
    'någonsin skänkt till en välgörenhetsorganisation',
    'någonsin låtsats vara sjuk för att komma ur något',
    'någonsin stått upp en dejt',
    'spökat någon',
    'haft sex på en strand',
    'någonsin blivit kär',
];