export default [
    'Jag har aldrig någonsin spelat pajas på skolan eller jobbet',
    'Jag har aldrig stulit något',
    'Jag har aldrig missat ett flyg',
    'Jag har aldrig  någonsin fyllt mitt ex',
    'Jag har aldrig kört motorcykel',
    'Jag har aldrig förlorat ett vad',
    'Jag har aldrig någonsin gått vilse ensam i ett främmande land',
    'Jag har aldrig mutat någon',
    'Jag har aldrig  någonsin gått i skinny-dipping',
    'Jag har aldrig någonsin varit otrogen mot någon',
    'Jag har aldrig sjungit karaoke',
    'Jag har aldrig brutit ett ben',
    'Jag har aldrig någonsin bott ensam',
    'Jag har aldrig varit på en yacht',
    'Jag har aldrig varit på tv',
    'Jag har aldrig varit på en blind date',
    'Jag har aldrig ljugit för polisen',
    'Jag har aldrig tatuerat mig',
    'Jag har aldrig använt ett falskt ID',
    'Jag har aldrig gjort slut med någon',
    'Jag har aldrig  någonsin blivit seriöst bakfull',
    'Jag har aldrig använt någon annans tandborste',
    'Jag har aldrig täppt till någon annans toalett',
    'Jag har aldrig någonsin somnat offentligt',
    'Jag har aldrig  någonsin kysst någon offentligt',
    'Jag har aldrig någonsin slagits offentligt',
    'Jag har aldrig  någonsin ätit och rusat',
    'Jag har aldrig vunnit på lotteriet',
    'Jag har aldrig behövt gå till domstol',
    'Jag har aldrig varit på ett målbröllop',
    'Jag har aldrig ljugit för en chef',
    'Jag har aldrig  någonsin kraschat ett bröllop',
    'Jag har aldrig  någonsin kysst mer än en person på 24 timmar',
    'Jag har aldrig skämtat någon',
    'Jag har aldrig någonsin haft ett one-night stand',
    'Jag har aldrig skänkt bort en gåva',
    'Jag har aldrig trollat ​​någon på sociala medier',
    'Jag har aldrig någonsin klättrat ut genom ett fönster',
    'Jag har aldrig någonsin kört över en trottoarkant',
    'Jag har aldrig  någonsin skrattat så mycket att jag kissade på byxorna som vuxen',
    'Jag har aldrig någonsin kommit på fel tåg eller buss',
    'Jag har aldrig skickat en sext',
    'Jag har aldrig någonsin förbannat på en plats för tillbedjan',
    'Jag har aldrig snokat igenom någons saker',
    'Jag har aldrig testat marijuana',
    'Jag har aldrig  någonsin gått 24 timmar utan att duscha',
    'Jag har aldrig någonsin behövt ta en promenad av skam',
    'Jag har aldrig någonsin åkt på en ensamsemester',
    'Jag har aldrig åkt på en roadtrip',
    'Jag har aldrig någonsin ätit en hel pizza själv',
    'Jag har aldrig någonsin räddat ett liv',
    'Jag har aldrig tatuerat mig',
    'Jag har aldrig någonsin velat vara med i en dokusåpa',
    'Jag har aldrig anlagt en eld',
    'Jag har aldrig  någonsin blivit stoppad av flygplatssäkerhet',
    'Jag har aldrig någonsin blivit viral på nätet',
    'Jag har aldrig någonsin lämnat tuggummi i ett offentligt utrymme',
    'Jag har aldrig sovit utomhus en hel natt',
    'Jag har aldrig sprungit ett maraton',
    'Jag har aldrig någonsin gett/fått en lapdance',
    'Jag har aldrig någonsin hållit ett tal inför 100 personer eller fler',
    'Jag har aldrig slappnat av i en offentlig pool',
    'Jag har aldrig någonsin ljugit för min bästa vän om vem jag var med',
    'Jag har aldrig någonsin varit i en Disneypark',
    'Jag har aldrig haft en trekant',
    'Jag har aldrig lämnat någon på läsning',
    'Jag har aldrig någonsin somnat under sex',
    'Jag har aldrig ljugit om min ålder',
    'Jag har aldrig någonsin hittat på en berättelse om någon som inte var verklig',
    'Jag har aldrig någonsin trott att något var hemsökt',
    'Jag har aldrig någonsin deltagit i en protest',
    'Jag har aldrig någonsin haft sömnförlamning',
    'Jag har aldrig  någonsin varit alibi för en lögnaktig vän',
    'Jag har aldrig  någonsin dragit en helnatter',
    'Jag har aldrig någonsin spelat rollspel',
    'Jag har aldrig ångrat en ursäkt',
    'Jag har aldrig  någonsin låtsats som att jag var trött på uppmärksamhet',
    'Jag har aldrig någonsin ogillat något som jag lagat',
    'Jag har aldrig någonsin tagit bort ett inlägg på sociala medier för att det inte fått tillräckligt många likes',
    'Jag har aldrig någonsin spenderat mer än 100 dollar på en topp',
    'Jag har aldrig kastat en drink på någon',
    'Jag har aldrig någonsin burit någon annans underkläder',
    'Jag har aldrig rest till Europa',
    'Jag har aldrig testat en trendig diet',
    'Jag har aldrig någonsin gått på en strippklubb',
    'Jag har aldrig någonsin bråkat en hel serie på en dag',
    'Jag har aldrig testat psykedelika',
    'Jag har aldrig någonsin träffat någon känd',
    'Jag har Aldrig någonsin blivit streaking',
    'Jag har aldrig varit med i ett idrottslag',
    'Jag har aldrig någonsin maxat ett kreditkort',
    'Jag har aldrig varit blackout full',
    'Jag har aldrig varit förlovad',
    'Jag har aldrig gift mig',
    'Jag har aldrig någonsin skänkt till en välgörenhetsorganisation',
    'Jag har aldrig  någonsin låtsats vara sjuk för att komma ur något',
    'Jag har aldrig  någonsin stått upp en dejt',
    'Jag har aldrig spökat någon',
    'Jag har aldrig haft sex på en strand',
    'Jag har aldrig någonsin blivit kär',
];