export default [
    'bli rik?',
    'gå med i Cirque Du Soleil?',
    'gå vilse i vildmarken?',
    'gå vilse i sitt eget kvarter?',
    'gifta sig i Vegas?',
    'bli en kändis?',
    'gifta sig med en kändis?',
    'bli en chef babe?',
    'skriva en bästsäljande bok?',
    'vinna en tv-sänd talangshow?',
    'misslyckas olyckligt (med avsikt) under en tv-sänd talangshow?',
    'gifta sig med sin gymnasieälskling?',
    'bli skadad av något dumt?',
    'vinna JEOPARDY?',
    'med största sannolikhet att dö först i en skräckfilm?',
    'har ett eget reality-program?',
    'bli en influencer?',
    'prova den senaste "galna" frisyren?',
    'klippa sin egen lugg?',
    'fallskärmshopp?',
    'fastnas för att du ska dippa?',
    'har haft sin första kyss före alla andra?',
    'sälja alla sina ägodelar och flytta till Tibet?',
    'har du en pinsam tatuering?',
    'har du det bästa pokeransiktet?',
    'bli en hacker?',
    'kandidera som president?',
    'gå med i FBI eller CIA?',
    'bli en kattdam?',
    'bli en TikTok-stjärna?',
    'resa till de mest främmande länderna?',
    'flytta till ett främmande land?',
    'har du massor av barn?',
    'bestämma dig för att inte skaffa barn?',
    'bli en HGTV-stjärna?',
    'spela i WNBA?',
    'har ett spökemöte?',
    'tjäna den första miljonen?',
    'leva längst?',
    'uppfinna en som sett på TV-produkt?',
    'bli nunna?',
    'komma sent till sitt eget bröllop?',
    'köpa en djurpark (som den där Matt Damon-filmen)?',
    'få flest tatueringar?',
    'utveckla konstiga fobier?',
    'gråta på bio?',
    'hamna i Guinness World Records?',
    'vinna en Grammis?',
    'flytta till ett annat land?',
    'äta något från marken?',
    'åka på ett rymduppdrag?',
    'bli fattig',
    'lyssna på klassisk musik?',
    'gå till museet väldigt ofta?',
    'gå på en Justin Bieber-konsert?',
    'gå på en Beyonce-konsert?',
    'äter chokladtäckta kackerlackor?',
    'vara uppe hela natten och titta på tv?',
    'vara vaken hela natten och rulla på sin telefon?',
    'ge alla sina pengar till välgörenhet?',
    'vinna ett ädelt pris?',
    'lyckas som en personlighet i luften?',
    'bli utslängd från en nöjespark?',
    'läsa varje bok på biblioteket?',
    'inte kunna hålla en hemlighet till varje pris?',
    'gifta sig?',
    'gifta sig med sin hund?',
    'åka på en ensamsemester?',
    'gå på en konsert ensam?',
    'klä upp till Halloween?',
    'försvinna i ett år?',
    'har du ett barn?',
    'vinner 1 miljon dollar i spel?',
    'bli en stor VD?',
    'Bungee jump?',
    'gå med i militären?',
    'äter du spagetti med sirap som Buddy from Elf?',
    'vinna stort i Vegas?',
    'gå på vandring med främlingar?',
    'prata med djur?',
    'skrika medan du tittar på en sorglig film?',
    'spendera mest pengar på att shoppa?',
    'hamnar du på Broadway?',
    'gå i pension och leva ut sina dagar på ett kryssningsfartyg?',
    'vinna en pajätningstävling?',
    'misslyckas olyckligt på Tetris?',
    'skära Thanksgiving-kalkonen?',
    'äter du något från golvet?',
    'vänta till kvällen innan med att plugga till ett prov?',
    'skaffa ett barn först?',
    'bli jagad av ett vilt djur?'
];